In [18]:
import geopandas as gpd

f = gpd.read_file('datasets/crash_data.geojson')

In [22]:
f.head()

,ACCIDENT_NO,ACCIDENT_DATE,ACCIDENT_TIME,ACCIDENT_TYPE,DAY_OF_WEEK,DCA_CODE,DCA_CODE_DESCRIPTION,LIGHT_CONDITION,POLICE_ATTEND,ROAD_GEOMETRY,SEVERITY,SPEED_ZONE,RUN_OFFROAD,ROAD_NAME,ROAD_TYPE,ROAD_ROUTE_1,LGA_NAME,DTP_REGION,LATITUDE,LONGITUDE,VICGRID_X,VICGRID_Y,TOTAL_PERSONS,INJ_OR_FATAL,FATALITY,SERIOUSINJURY,OTHERINJURY,NONINJURED,MALES,FEMALES,BICYCLIST,PASSENGER,DRIVER,PEDESTRIAN,PILLION,MOTORCYCLIST,UNKNOWN,PED_CYCLIST_5_12,PED_CYCLIST_13_18,OLD_PED_65_AND_OVER,OLD_DRIVER_75_AND_OVER,YOUNG_DRIVER_18_25,NO_OF_VEHICLES,HEAVYVEHICLE,PASSENGERVEHICLE,MOTORCYCLE,PT_VEHICLE,DEG_URBAN_NAME,SRNS,RMA,DIVIDED,STAT_DIV_NAME,geometry
0,T20120000009,20120101,022500,Collision with a fixed object,Sunday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,Dark No street lights,Yes,Not at intersection,Other injury accident,100 km/hr,Yes,WESTERNPORT,ROAD,5707,BAW BAW,GIPPSLAND,-38.234957,145.726709,2563628.962,2362700.434,2,2,0,0,2,0,2,0,0,1,1,0,0,0,0,0,0,0,0,1,1.0,0.0,1.0,0.0,0.0,RURAL_VICTORIA,C,Arterial Other,Undivided,Country,POINT (145.72671 -38.23496)
1,T20120000012,20120101,020000,Collision with vehicle,Sunday,110,CROSS TRAFFIC(INTERSECTIONS ONLY),Dark Street lights on,Yes,Cross intersection,Serious injury accident,80 km/hr,No,SPRINGVALE,ROAD,2400,MONASH,INNER METRO,-37.903541,145.161404,2514194.683,2399718.586,3,1,0,1,0,2,2,0,0,1,2,0,0,0,0,0,0,0,0,0,2.0,0.0,2.0,0.0,0.0,MELB_URBAN,None,None,None,Metro,POINT (145.1614 -37.90354)
2,T20120000013,20120101,033500,Collision with vehicle,Sunday,160,VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...,Dark Street lights on,Yes,T intersection,Serious injury accident,60 km/hr,No,CLARINDA,ROAD,5306,KINGSTON,INNER METRO,-37.935940,145.098848,2508689.410,2396130.003,1,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,2.0,0.0,2.0,0.0,0.0,MELB_URBAN,None,Arterial Other,Undivided,Metro,POINT (145.09885 -37.93594)
3,T20120000018,20120101,051500,Collision with a fixed object,Sunday,173,RIGHT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,Dark No street lights,Yes,Cross intersection,Other injury accident,100 km/hr,Yes,STURT,HIGHWAY,2610,MILDURA,LODDON MALLEE,-34.215874,142.043881,2227360.371,2804744.001,1,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1.0,0.0,1.0,0.0,0.0,RURAL_VICTORIA,A,Arterial Highway,Undivided,Country,POINT (142.04388 -34.21587)
4,T20120000021,20120101,073000,Collision with a fixed object,Sunday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,Day,Yes,Not at intersection,Other injury accident,50 km/hr,Yes,WILLIAM,ROAD,9999,MORNINGTON PENINSULA,GREATER METRO,-38.369561,144.777930,2480590.789,2347977.747,3,2,0,0,2,1,2,1,0,2,1,0,0,0,0,0,0,0,0,1,1.0,0.0,1.0,0.0,0.0,MELB_URBAN,None,Local Road,Undivided,Metro,POINT (144.77793 -38.36956)

In [2]:
import pandas as pd

node_file = pd.read_csv("datasets/node.csv")
post_codes=pd.read_csv("datasets/melbourne_postcodes.csv")

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
node_file.head()

,ACCIDENT_NO,NODE_ID,NODE_TYPE,AMG_X,AMG_Y,LGA_NAME,LGA NAME ALL,DEG_URBAN_NAME,LATITUDE,LONGITUDE,POSTCODE_CRASH
0,T20120000009,249102,N,2563628.962,2362700.434,BAW BAW,BAW BAW,RURAL_VICTORIA,-38.234957,145.726709,3981
1,T20120000012,41780,N,2514194.683,2399718.586,MONASH,MONASH,MELB_URBAN,-37.903541,145.161404,3170
2,T20120000013,69811,I,2508689.410,2396130.003,KINGSTON,KINGSTON,MELB_URBAN,-37.935940,145.098848,3169
3,T20120000018,22636,I,2227360.371,2804744.001,MILDURA,MILDURA,RURAL_VICTORIA,-34.215874,142.043881,3505
4,T20120000021,248597,N,2480590.789,2347977.747,MORNINGTON PENINSULA,MORNINGTON PENINSULA,MELB_URBAN,-38.369561,144.777930,3942

In [5]:
post_codes.head()

,geo_point_2d,geo_shape,mccid_gis,mccid_int,suburb
0,"-37.83759427054876, 144.98291661287664","{""coordinates"": [[[[144.98502208625717, -37.84...",5,3141,SOUTH YARRA
1,"-37.81442135100178, 144.98255916174276","{""coordinates"": [[[[144.9713614831405, -37.807...",13,3002,EAST MELBOURNE
2,"-37.79215550566622, 144.92130845946264","{""coordinates"": [[[[144.9360757084024, -37.802...",17,3031,KENSINGTON
3,"-37.782801479230415, 144.91100723310632","{""coordinates"": [[[[144.90659164765404, -37.78...",1,3032,ASCOT VALE
4,"-37.79847805173012, 144.94482493930565","{""coordinates"": [[[[144.95359698146945, -37.79...",3,3051,NORTH MELBOURNE

In [6]:
# Merge the dataframes on POSTCODE_CRASH and mccid_int
merged_data = pd.merge(node_file, post_codes, left_on='POSTCODE_CRASH', right_on='mccid_int')

# Display the merged dataframe
merged_data.head()

,ACCIDENT_NO,NODE_ID,NODE_TYPE,AMG_X,AMG_Y,LGA_NAME,LGA NAME ALL,DEG_URBAN_NAME,LATITUDE,LONGITUDE,POSTCODE_CRASH,geo_point_2d,geo_shape,mccid_gis,mccid_int,suburb
0,T20120000097,37583,I,2497517.608,2407639.426,PORT PHILLIP,"MELBOURNE,PORT PHILLIP",MELB_URBAN,-37.832280,144.971800,3004,"-37.82894848788476, 144.97861771627643","{""coordinates"": [[[[144.96824980168788, -37.81...",12,3004,ST KILDA ROAD
1,T20120000124,248613,N,2493672.289,2413980.383,MOONEE VALLEY,MOONEE VALLEY,MELB_URBAN,-37.775129,144.928171,3032,"-37.782801479230415, 144.91100723310632","{""coordinates"": [[[[144.90659164765404, -37.78...",1,3032,ASCOT VALE
2,T20120000139,36366,I,2497476.572,2412045.745,MELBOURNE,"MELBOURNE,YARRA",MELB_URBAN,-37.792579,144.971349,3054,"-37.78706872638871, 144.96355128708092","{""coordinates"": [[[[144.96522746522837, -37.79...",10,3054,CARLTON NORTH
3,T20120000296,273226,N,2496297.153,2410345.988,MELBOURNE,MELBOURNE,MELB_URBAN,-37.807890,144.957949,3000,"-37.81345809172053, 144.96309518154132","{""coordinates"": [[[[144.95472481534262, -37.79...",15,3000,MELBOURNE
4,T20120000334,66220,I,2493900.026,2408819.288,MELBOURNE,MELBOURNE,MELB_URBAN,-37.821633,144.930714,3207,"-37.83135640184151, 144.9122365023871","{""coordinates"": [[[[144.9200817613856, -37.819...",2,3207,PORT MELBOURNE

In [7]:
filtered_data = merged_data[['ACCIDENT_NO', 'LATITUDE', 'LONGITUDE','geo_point_2d','geo_shape', 'suburb', 'POSTCODE_CRASH']]

In [8]:
filtered_data.head()

,ACCIDENT_NO,LATITUDE,LONGITUDE,geo_point_2d,geo_shape,suburb,POSTCODE_CRASH
0,T20120000097,-37.832280,144.971800,"-37.82894848788476, 144.97861771627643","{""coordinates"": [[[[144.96824980168788, -37.81...",ST KILDA ROAD,3004
1,T20120000124,-37.775129,144.928171,"-37.782801479230415, 144.91100723310632","{""coordinates"": [[[[144.90659164765404, -37.78...",ASCOT VALE,3032
2,T20120000139,-37.792579,144.971349,"-37.78706872638871, 144.96355128708092","{""coordinates"": [[[[144.96522746522837, -37.79...",CARLTON NORTH,3054
3,T20120000296,-37.807890,144.957949,"-37.81345809172053, 144.96309518154132","{""coordinates"": [[[[144.95472481534262, -37.79...",MELBOURNE,3000
4,T20120000334,-37.821633,144.930714,"-37.83135640184151, 144.9122365023871","{""coordinates"": [[[[144.9200817613856, -37.819...",PORT MELBOURNE,3207

In [10]:
accident=pd.read_csv("datasets/accident.csv")

In [11]:
# Select specific columns
accident_final = accident[['ACCIDENT_NO', 'ACCIDENT_DATE', 'ACCIDENT_TIME', 'ACCIDENT_TYPE', 'ACCIDENT_TYPE_DESC', 'SEVERITY']]

# Display the selected columns DataFrame
accident_final.head()

,ACCIDENT_NO,ACCIDENT_DATE,ACCIDENT_TIME,ACCIDENT_TYPE,ACCIDENT_TYPE_DESC,SEVERITY
0,T20120000009,2012-01-01,02:25:00,4,Collision with a fixed object,3
1,T20120000012,2012-01-01,02:00:00,1,Collision with vehicle,2
2,T20120000013,2012-01-01,03:35:00,1,Collision with vehicle,2
3,T20120000018,2012-01-01,05:15:00,4,Collision with a fixed object,3
4,T20120000021,2012-01-01,07:30:00,4,Collision with a fixed object,3

In [12]:
final_merged_data = pd.merge(filtered_data, accident_final, on='ACCIDENT_NO')

In [20]:
final_merged_data.head()
final_merged_data.dtypes

ACCIDENT_NO            object
LATITUDE              float64
LONGITUDE             float64
geo_point_2d           object
geo_shape              object
suburb                 object
POSTCODE_CRASH          int64
ACCIDENT_DATE          object
ACCIDENT_TIME          object
ACCIDENT_TYPE           int64
ACCIDENT_TYPE_DESC     object
SEVERITY                int64
dtype: object

In [14]:
# Export the DataFrame to a CSV file
final_merged_data.to_csv('crash.csv', index=False)

In [15]:
crash_data=pd.read_csv("crash.csv")

In [5]:
import pandas as pd
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import plotly.graph_objs as go

# Aggregate data for choropleth map
suburb_counts = crash_data.groupby('suburb').size().reset_index(name='ACCIDENT_COUNT')

# Combine with lat/lon data
suburb_counts = suburb_counts.merge(crash_data[['suburb', 'LATITUDE', 'LONGITUDE']].drop_duplicates(), on='suburb')

# Create the Dash app
app = Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Accidents by Suburb", style={'text-align': 'center'}),
    dcc.Graph(id='choropleth-map'),
    dcc.Graph(id='bar-chart')
])

# Callback for updating the choropleth map
@app.callback(
    Output('choropleth-map', 'figure'),
    Input('choropleth-map', 'clickData')
)
def update_map(clickData):
    fig = px.scatter_mapbox(
        suburb_counts,
        lat="LATITUDE",
        lon="LONGITUDE",
        size="ACCIDENT_COUNT",
        color="ACCIDENT_COUNT",
        hover_name="suburb",
        hover_data={"LATITUDE": False, "LONGITUDE": False},
        color_continuous_scale="Viridis",
        zoom=8,
        mapbox_style="carto-positron"
    )
    fig.update_layout(
        title="Accidents by Suburb",
        mapbox=dict(center={"lat": -37.8136, "lon": 144.9631}, zoom=10),
        margin={"r":0,"t":0,"l":0,"b":0},
        height=600
    )
    return fig

# Callback for updating the bar chart
@app.callback(
    Output('bar-chart', 'figure'),
    Input('choropleth-map', 'clickData')
)
def update_bar_chart(clickData):
    if clickData:
        suburb = clickData['points'][0]['hovertext']
        filtered_df = crash_data[crash_data['suburb'] == suburb]
        bar_data = filtered_df['ACCIDENT_TYPE_DESC'].value_counts().reset_index()
        bar_data.columns = ['ACCIDENT_TYPE_DESC', 'COUNT']
        
        bar_fig = px.bar(
            bar_data,
            x='ACCIDENT_TYPE_DESC',
            y='COUNT',
            color='COUNT',
            color_continuous_scale='Blues',
            title=f"Accident Types in {suburb}",
            labels={'ACCIDENT_TYPE_DESC': 'Accident Type', 'COUNT': 'Number of Accidents'}
        )
        
        bar_fig.update_layout(
            title={'x':0.5, 'xanchor': 'center'},
            xaxis_title="Accident Type",
            yaxis_title="Number of Accidents",
            template='plotly_white'
        )
        return bar_fig
    
    return go.Figure()

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8051)